
export const serverHostList =  [
  { "clientEndpoint": "localhost", "serverEndpoint": "http://localhost:8104", "title": "Elabs", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"http://localhost:4200/#/search", "theme_setting": {
        "header_bg_color": "#fcfcfc",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "", 
        "footer_bg": "#77bce8",
        "theme_color": "#77bce8",
        "active_bg_color": "#e4f2fa",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
  },

  { "clientEndpoint": "drugs.medicea.in", "serverEndpoint": "https://sitservermedicea.medicea.in", "title": "Medicea Technology", "google_map": "false", "menu_type":"Horizontal", "folder": "medicea", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "app.medicea.in", "serverEndpoint": "https://servermedicea.medicea.in", "title": "Medicea Technology", "google_map": "false", "menu_type":"Horizontal", "medicea": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "lims.inventlands.com", "serverEndpoint": "https://prodinventlandserver.e-labs.ai", "title": "Inventlands", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "testlims.inventlands.com", "serverEndpoint": "https://testinventlandserver.e-labs.ai", "title": "Inventlands", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "sit-sanskar.e-labs.ai", "serverEndpoint": "https://sitsanskarserver.e-labs.ai", "title": "Sanskar", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "sanskar.e-labs.ai", "serverEndpoint": "https://prodsanskarserver.e-labs.ai", "title": "Sanskar", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"",    "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "itllabs.e-labs.ai", "serverEndpoint": "https://serveritllabs.e-labs.ai", "title": "Itllabs", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "hardgoodslabs.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai", "title": "Hardgoodslabs", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "demolab.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai", "title": "Demolab", "google_map": "false", "menu_type":"Horizontal", "folder": "elabs-client", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "",
        "theme_color": "",
        "active_bg_color": "",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    { "clientEndpoint": "test.ascgroup.in", "serverEndpoint": "https://sitserverascgroup.e-labs.ai", "title": "ASC group", "google_map": "false", "menu_type":"Vertical", "folder": "asc-group", "temp_name": "temp1", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "#fcfcfc",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "#77bce8",
        "theme_color": "#77bce8",
        "active_bg_color": "#e4f2fa",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },
    

    { "clientEndpoint": "itclabs.e-labs.ai", "serverEndpoint": "https://serveritclabs.e-labs.ai", "title": "Itclabs", "google_map": "false", "menu_type":"Horizontal", "folder": "itclabs", "temp_name": "temp2", "theme": "theme1", "redirect_url":"", "theme_setting": {
      "header_bg_color": "#665852",
      "header_txt_color": "#ffffff",
      "header_txt_hover_color": "",
      "header_icon_color": "#ffffff",
      "header_icon_hover_color": "#ffffff",
      "btn_color": "",
      "btn_hover_color": "",
      "footer_bg": "#212121",
      "theme_color": "#665852",
      "active_bg_color": "#e0dedc",
      "popup_header_bg": "",
      "form_label_bg": "",
    }},
    { "clientEndpoint": "uat-itclabs.e-labs.ai", "serverEndpoint": "https://uatserveritclabs.e-labs.ai", "title": "Itclabs", "google_map": "false","menu_type":"Horizontal", "folder": "itclabs", "temp_name": "temp2", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "#665852",
        "header_txt_color": "#ffffff",
        "header_txt_hover_color": "",
        "header_icon_color": "#ffffff",
        "header_icon_hover_color": "#ffffff",
        "btn_color": "",
        "btn_hover_color": "",
        "footer_bg": "#212121",
        "theme_color": "#665852",
        "active_bg_color": "#e0dedc",
        "popup_header_bg": "",
        "form_label_bg": "",
      }
    },


    { "clientEndpoint": "qualiteklab.e-labs.ai", "serverEndpoint": "https://serverqualiteklab.e-labs.ai", "title": "Qualitek Labs", "google_map": "false","menu_type":"Vertical", "folder": "qualitek", "temp_name": "temp3", "theme": "theme1", "redirect_url":"", "theme_setting": {
        "header_bg_color": "#fcfcfc",
        "header_txt_color": "",
        "header_txt_hover_color": "",
        "header_icon_color": "",
        "header_icon_hover_color": "",
        "btn_color": "#64B3E5",
        "btn_hover_color": "",
        "footer_bg": "#232324",
        "theme_color": "#1d9527",
        "active_bg_color": "#e0f0e1",
        "popup_header_bg": "#CEE7F7",
        "form_label_bg": "#E4F2FA",
      }
    },
    { "clientEndpoint": "uat-qualiteklab.e-labs.ai", "serverEndpoint": "https://uatserverqualiteklab.e-labs.ai", "title": "Qualitek Labs", "google_map": "false", "menu_type":"Vertical", "folder": "qualitek", "temp_name": "temp3", "theme": "theme1", "redirect_url":"", "theme_setting": {
          "header_bg_color": "#fcfcfc",
          "header_txt_color": "",
          "header_txt_hover_color": "",
          "header_icon_color": "",
          "header_icon_hover_color": "",
          "btn_color": "#64B3E5",
          "btn_hover_color": "",
          "footer_bg": "#232324",
          "theme_color": "#1d9527",
          "active_bg_color": "#e0f0e1",
          "popup_header_bg": "#CEE7F7",
          "form_label_bg": "#E4F2FA",
        }
    },
    { "clientEndpoint": "dev-qualiteklab.e-labs.ai", "serverEndpoint": "https://devserverqualiteklab.e-labs.ai",  "title": "Qualitek Labs", "google_map": "false","menu_type":"Vertical", "folder": "qualitek", "temp_name": "temp3", "theme": "theme1", "redirect_url":"", "theme_setting": {
          "header_bg_color": "#fcfcfc",
          "header_txt_color": "",
          "header_txt_hover_color": "",
          "header_icon_color": "",
          "header_icon_hover_color": "",
          "btn_color": "#64B3E5",
          "btn_hover_color": "",
          "footer_bg": "#232324",
          "theme_color": "#1d9527",
          "active_bg_color": "#e0f0e1",
          "popup_header_bg": "#CEE7F7",
          "form_label_bg": "#E4F2FA",
        }
      },
        
  ]
