export const serverHostList = [
  {"clientEndpoint": "localhost", "serverEndpoint": "http://localhost:8104"},
  {"clientEndpoint": "sit.e-labs.ai", "serverEndpoint": "https://sitserverelabs.e-labs.ai"},
  {"clientEndpoint": "dev.e-labs.ai", "serverEndpoint": "https://devserverelabs.e-labs.ai"}, 
  {"clientEndpoint": "uat.e-labs.ai", "serverEndpoint": "https://uatserverelabs.e-labs.ai"},  
  {"clientEndpoint": "sit-sanskar.e-labs.ai", "serverEndpoint": "https://sitsanskarserver.e-labs.ai"},
  {"clientEndpoint": "lims-sanskar.e-labs.ai", "serverEndpoint": "https://prodsanskarserver.e-labs.ai"},  
  {"clientEndpoint": "hardgoodslabs.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientEndpoint": "demolab.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientEndpoint": "lite-demolab.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientEndpoint": "standard-demolab.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientEndpoint": "test.ascgroup.in", "serverEndpoint": "https://sitserverascgroup.e-labs.ai"},
  {"clientEndpoint": "erp.ascgroup.in", "serverEndpoint": "https://prodserverascgroup.e-labs.ai"},
  {"clientEndpoint": "itclabs.e-labs.ai", "serverEndpoint": "https://serveritclabs.e-labs.ai"},
  {"clientEndpoint": "dev-itclabs.e-labs.ai", "serverEndpoint": "https://devserveritclabs.e-labs.ai"},
  {"clientEndpoint": "uat-itclabs.e-labs.ai", "serverEndpoint": "https://uatserveritclabs.e-labs.ai"},
  {"clientEndpoint": "lims.itclabs.com", "serverEndpoint": "https://prodserveritclabs.e-labs.ai"},
  {"clientEndpoint": "qualiteklab.e-labs.ai", "serverEndpoint": "https://serverqualiteklab.e-labs.ai"},
  {"clientEndpoint": "uat-qualiteklab.e-labs.ai", "serverEndpoint": "https://uatserverqualiteklab.e-labs.ai"},
  {"clientEndpoint": "lims.qualiteklab.com", "serverEndpoint": "https://prodserverqualiteklab.e-labs.ai"},
  {"clientEndpoint": "dev-qualiteklab.e-labs.ai", "serverEndpoint": "https://devserverqualiteklab.e-labs.ai"},
  {"clientEndpoint": "sit-hitech.e-labs.ai", "serverEndpoint": "https://sithitechserver.e-labs.ai"},
  {"clientEndpoint": "lims-hitech.e-labs.ai", "serverEndpoint": "https://prodhitechserver.e-labs.ai"},
  {"clientEndpoint": "sit-aalbiosciences.e-labs.ai", "serverEndpoint": "https://sitaalbiosciencesserver.e-labs.ai"},
  {"clientEndpoint": "lims-aalbiosciences.e-labs.ai", "serverEndpoint": "https://prodaalbiosciencesserver.e-labs.ai"},
  {"clientEndpoint": "bbsr-lims.qualiteklab.com", "serverEndpoint": "https://prodserverbbsrqualiteklab.e-labs.ai"},
  {"clientEndpoint": "sit-multani.e-labs.ai", "serverEndpoint": "https://sitmultaniserver.e-labs.ai"},
  {"clientEndpoint": "app.multani.com", "serverEndpoint": "http://server.multani.com:30051"},
  {"clientEndpoint": "food.multani.com", "serverEndpoint": "http://server.multani.com:30051"},
  {"clientEndpoint": "lims-pharma-multani.e-labs.ai", "serverEndpoint": "https://prodmultaniserver.e-labs.ai"},
  {"clientEndpoint": "lims-food-multani.e-labs.ai", "serverEndpoint": "https://prodmultaniserver.e-labs.ai"},
  {"clientEndpoint": "lims-multani.e-labs.ai", "serverEndpoint": "https://sitmultaniserver.e-labs.ai"},  
  {"clientEndpoint": "web.sralabs.com", "serverEndpoint": "https://prodsatiateserver.e-labs.ai"}
]

