// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2d92113c-988b-4fa4-9857-cc53a8818d85",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_hH0UXEwb5",
    "aws_user_pools_web_client_id": "7ml87ka4pu6o91l3qodbafa0eq",
    "oauth": {}
};


export default awsmobile;
