# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Angular CI with Node - awsprodclient

on:
  push:
    branches: [ awsprodclient-dummy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    ########################### Elabs Aws - ###########################
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
    
    
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Installing source NPM dependencies...
      run: npm install
      
    - name: Installing Angular
      run: npm install -g @angular/cli@11.0.5
    
    - name: Set Node Options
      run: echo "NODE_OPTIONS=--max_old_space_size=${{ secrets.RAM }}" >> $GITHUB_ENV
    
    - name: Building
      run: ng build --configuration=develop
     

  # Deploy LIMS on Prod Environments Labs
    - name: Clean up existing deployment - All Production Lims
      run: aws s3 rm s3://prodclientslims.e-labs.ai --recursive

    - name: Upload data
      run: aws s3 sync dist s3://prodclientslims.e-labs.ai
    
    - name: Extract Distributions
      run: |
        distributions=$(aws cloudfront list-distributions  --query "DistributionList.Items[*].{id:Id,origin:Origins.Items[0].Id}[?origin=='prodclientslims.e-labs.ai.s3.ap-south-1.amazonaws.com'].id" --output json)
        echo $distributions >> distributions.json
        
    - name: List of the GitHub Actions environment variables on Ubuntu
      run: ls -lrt
      
    - name: Extract all distibutions from distributions file
      uses: sergeysova/jq-action@v2
      id: keywords
      with:
        cmd: 'jq .[] distributions.json -r'
        multiline: true
      
    - name: Clear Cache all distributions
      run: |
        keywords="${{ steps.keywords.outputs.value }}"
        for keyword in $keywords; do
           echo "clearing cache for $keyword"
           aws cloudfront create-invalidation --distribution-id $keyword --paths '/*'
        done
