# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker Build - Release 
on:
  push:
    branches: [ 'release/v**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    ########################### Elabs Aws - ###########################
    # Elabs Aws
    - name: Configure AWS credentials Elabs
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ELABS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ELABS_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.ELABS_REGION }}

    - name: Set Git Env
      run: echo $GITHUB_ENV
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: List of the GitHub Actions environment variables on Ubunt
      run: env  

    - name: Get VERSION
      run: echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV
      
    - name: Get Availability
      run: echo "Availability=UI-GA" >> $GITHUB_ENV
    
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.2'
    
    - name: Installing NPM and Angular
      run: |         
        export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ui-libs --domain-owner ${{ secrets.ELABS_DOMAIN_OWNER }} --region ap-south-1 --query authorizationToken --output text`
        aws codeartifact login --tool npm --repository ui-library --domain ui-libs --domain-owner ${{ secrets.ELABS_DOMAIN_OWNER }} --region ap-south-1
        echo $CODEARTIFACT_AUTH_TOKEN        
        npm install -g @angular/cli@15.2.10
        npm install
    
    - name: Set Node Options
      run: echo "NODE_OPTIONS=--max_old_space_size=${{ secrets.RAM }}" >> $GITHUB_ENV
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: elabs-client
        #IMAGE_TAG: $VERSION-$GITHUB_RUN_NUMBER-$Availability -> not working
      run: |
        ls -lrt
        ng build --configuration=production
        ls -lrt
        pwd
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION-$GITHUB_RUN_NUMBER-$Availability .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION-$GITHUB_RUN_NUMBER-$Availability