# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Angular CI with Node - SIT
on:
  push:
    branches: [ testasc ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    ########################### Elabs Aws - ###########################
    # Elabs Aws
    - name: Configure AWS credentials Elabs
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
        
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ secrets.NODE_VERSION }}'
    
    - name: Installing source NPM dependencies...
      run: npm install
      
    - name: Installing Angular
      run: npm install -g @angular/cli
    
    
    - name: Set Node Options
      run: echo "NODE_OPTIONS=--max_old_space_size=${{ secrets.RAM }}" >> $GITHUB_ENV
    
    - name: Building
      run: ng build --configuration=${{ secrets.ENVIRONMENT_SIT }}
     


########################### Medicea Aws - ###########################
  # Medicea Aws
    - name: Configure AWS credentials Medicea
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MEDICEA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MEDICEA }}
        aws-region: ${{ secrets.REGION }}


  # Deploy  Asc Group Sit
    - name: Clean up existing deployment - Asc Group - Medicea
      run: aws s3 rm s3://test.ascgroup.in --recursive

    - name: Upload data
      run: aws s3 sync dist s3://test.ascgroup.in

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E1U1RL73RJW4LA --paths '/*'

