# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Angular CI with Node - DEVELOp
on:
  push:
    branches: [ feature/docker-images ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    ########################### Elabs Aws - ###########################
    # Elabs Aws
    - name: Configure AWS credentials Elabs
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MEDICEA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MEDICEA }}
        aws-region: ${{ secrets.REGION }}

    - name: Set Git Env
      run: echo $GITHUB_ENV
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: List of the GitHub Actions environment variables on Ubunt
      run: env  

    - name: Get VERSION
      run: echo "VERSION=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
      
    - name: Get Availability
      run: echo "Availability=RC" >> $GITHUB_ENV
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: elabs-client
        IMAGE_TAG: ${{ VERSION }}-${{ GITHUB_RUN_NUMBER }}-${{ Availability }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
