# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Angular CI with Node - Prod

on:
  push:
    branches: [ prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    ########################### Elabs Aws - ###########################
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
        
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ secrets.NODE_VERSION }}'
    
    - name: Installing source NPM dependencies...
      run: npm install
      
    - name: Installing Angular
      run: npm install -g @angular/cli
    
    
    - name: Set Node Options
      run: echo "NODE_OPTIONS=--max_old_space_size=${{ secrets.RAM }}" >> $GITHUB_ENV
    
    - name: Building
      run: ng build --configuration=${{ secrets.ENVIRONMENT_PRODUCTION }}
     
    # Deploy InventLands    
    - name: Clean up existing deployment - InventLands
      run: aws s3 rm s3://lims.inventlands.com --recursive

    - name: Upload data
      run: aws s3 sync dist s3://lims.inventlands.com

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E11PKSB8NSLBFD --paths '/*'

  # Deploy Sanskar
    - name: Clean up existing deployment - Sanskar
      run: aws s3 rm s3://sanskar.e-labs.ai --recursive

    - name: Upload data
      run: aws s3 sync dist s3://sanskar.e-labs.ai

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id EZM8OSIIJIZIC --paths '/*'
      
  # Deploy ItcLabs    
    - name: Clean up existing deployment - ItcLabs Dev
      run: aws s3 rm s3://lims.itclabs.com --recursive

    - name: Upload data
      run: aws s3 sync dist s3://lims.itclabs.com

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E2VR8P8C4U5JQ8 --paths '/*'

  # Deploy Qualitek Labs
    - name: Clean up existing deployment - Qualitek Labs
      run: aws s3 rm s3://lims.qualiteklab.com --recursive

    - name: Upload data
      run: aws s3 sync dist s3://lims.qualiteklab.com
      
    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E2DMYDKCSUDLCI --paths '/*'    
      
   
  # Deploy aalbiosciences Labs
    - name: Clean up existing deployment - Aalbiosciences Labs
      run: aws s3 rm s3://lims-aalbiosciences.e-labs.ai --recursive

    - name: Upload data
      run: aws s3 sync dist s3://lims-aalbiosciences.e-labs.ai
      
    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id EN9PMCW1EONN --paths '/*'    
      
  
  # Deploy Hitech Labs
    - name: Clean up existing deployment - Hitech Labs
      run: aws s3 rm s3://lims-hitech.e-labs.aiai --recursive

    - name: Upload data
      run: aws s3 sync dist s3://lims-hitech.e-labs.aiai
      
    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E15DYVRXMEU2LT --paths '/*'       
      
  # Deploy ItlLabs Labs
    - name: Clean up existing deployment - ItlLabs Labs
      run: aws s3 rm s3://lims-itllabs.e-labs.ai --recursive

    - name: Upload data
      run: aws s3 sync dist s3://lims-itllabs.e-labs.ai
      
    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E15K6937U00EIX --paths '/*'       
      
########################### Medicea Aws - ###########################
  # Medicea Aws
    - name: Configure AWS credentials Medicea
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MEDICEA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MEDICEA }}
        aws-region: ${{ secrets.REGION }}
    
    

  # Deploy  Asc Group Prod
    - name: Clean up existing deployment - Asc Group - Medicea
      run: aws s3 rm s3://erp.ascgroup.in --recursive

    - name: Upload data
      run: aws s3 sync dist s3://erp.ascgroup.in

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E2TSEGTFACTBCI --paths '/*'      

  # Deploy Medicea App    
    - name: Clean up existing deployment - Medicea App
      run: aws s3 rm s3://app.medicea.in --recursive

    - name: Upload data
      run: aws s3 sync dist s3://app.medicea.in

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id EQ8YH2PYATWGD --paths '/*'
