# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Angular CI with Node - DEVELOp
on:
  push:
    branches: [ develop1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    ########################### Elabs Aws - ###########################
    # Elabs Aws
    - name: Configure AWS credentials Elabs
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
        
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ secrets.NODE_VERSION }}'
    
    - name: Installing source NPM dependencies...
      run: npm install
      
    - name: Installing Angular
      run: npm install -g @angular/cli
    
    
    - name: Set Node Options
      run: echo "NODE_OPTIONS=--max_old_space_size=${{ secrets.RAM }}" >> $GITHUB_ENV
    
    - name: Building
      run: ng build --configuration=${{ secrets.ENVIRONMENT_SIT }}
     
  # Deploy ItcLabs    
    - name: Clean up existing deployment - ItcLabs Dev
      run: aws s3 rm s3://dev-itclabs.e-labs.ai --recursive

    - name: Upload data
      run: aws s3 sync dist s3://dev-itclabs.e-labs.ai

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E2Q0N8RC8S97A4 --paths '/*'

  # Deploy Qualitek Labs
    - name: Clean up existing deployment - Qualitek Labs
      run: aws s3 rm s3://dev-qualiteklab.e-labs.ai --recursive

    - name: Upload data
      run: aws s3 sync dist s3://dev-qualiteklab.e-labs.ai

    - name: Clean up cache
      run: aws cloudfront create-invalidation --distribution-id E2TBVCQ5FYGZF0 --paths '/*'
  
 
